# Base configs
baseurl: "https://iiey.github.io/photo"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by nemo"
subtitle: "See the world through my eyes!"
author: "nemo"
header:
 title: "Photography"
 subtitle: "by nemo"
footer:
 name: "Hey there, my name is nemo"
 bio: "I am a software developer in machine learning and computer vision, have passion in art and photography"
social_urls:
  twitter: "https://www.twitter.com/minhtrietl"
  linkedin: "https://in.linkedin.com/in/mt-ly"
  github: "https://www.github.com/iiey"
